<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0da34f72115817f22ca220a22f107947
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0da34f72115817f22ca220a22f107947::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0da34f72115817f22ca220a22f107947::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
